define({
	
	// EXTENSION.
	EXTENSION_NAME: "Simple-Sftp-Upload",
	
	TXT_SETTING:	"Connection setting file storage location",
	TXT_SETTING_ERROR:	"Connection setting file storage location is not set.",
	TXT_CONNECTING_SETTING:	"FTP/SFTP Connection Setting",
	TXT_FTP_SETTING:	"FTP/SFTP Setting",
	TXT_FTP_LOG:	"FTP/SFTP Connection Log",
	TXT_REFERENCE:	"Reference",
	TXT_TEST_UPLOAD:	"[SSFTP] Upload to test environment",
	TXT_TEST_UPLOAD2:	"Upload to test environment",
	TXT_TEST_UPLOAD2:	"Upload to test environment",
	TXT_SELECT_UPLOAD:	"[SSFTP] Upload selection file",
	TXT_PRODUCTION_UPLOAD:	"[SSFTP] Upload to production environment",
	TXT_PRODUCTION_UPLOAD2:	"Upload to production environment",
	TXT_ADD_MODIFY_LOG:	"[SSFTP] Add to modify log",
	TXT_MODIFY_LOG:	"Modify log",
	TXT_LOCAL_SAVE:	"Save to local folder",
	TXT_STORAGE_LOCATION:	"Storage location",
	TXT_SELECT_SAVE_FOLDER:	"Select save folder",
	TXT_CONNECTION_1:	"Please specify the location to save the connection setting file.",
	TXT_CONNECTION_2:	"* Please do not save in the place to publish to the server.",
	TXT_CONNECTION_3:	"* The connection setting file of all projects is saved.",
	TXT_SETTINGS_DIALOG_TYPE_FTP:	"FTP",
	TXT_SETTINGS_DIALOG_TYPE_SFTP:	"SFTP(SSH)",
	TXT_SETTINGS_DIALOG_TYPE_LOCAL:	"Local",
	TXT_CONNECTION_SETTING_NAME:	"Connection setting name",
	TXT_TESTING_ENVIRONMENT:	"Testing environment",
	TXT_TESTING_ENVIRONMENT_OPEN:	"Open test environment",
	TXT_PRODUCTION_ENVIRONMENT:	"Production environment",
	TXT_PRODUCTION_ENVIRONMENT_OPEN:	"Open production environment",
	TXT_CONNECTION_TYPE:	"Type",
	TXT_CONNECTION_HOST:	"Host",
	TXT_CONNECTION_PORT:	"Port",
	TXT_CONNECTION_USER_NAME:	"User Name",
	TXT_CONNECTION_PASSWORD:	"Password",
	TXT_CONNECTION_RSA:	"RSA private key",
	TXT_CONNECTION_SERVER_PATH:	"Server Path",
	TXT_CONNECTION_UPLOAD_ON_SAVE:	"Upload on Save",
	TXT_CONNECTION_SETTING_LOAD:	"Reading the configuration file",
	TXT_CONNECTION_SITE_URL:	"Public path",
	TXT_NO_CONNECTION_HOST:	"Connection destination is not set.",
	TXT_START_UPLOADING:	"Start uploading",
	TXT_START_UPLOADING_Q:	"Start upload queue",
	TXT_START_UPLOADING_Q_NOW:	"Running upload queue",
	TXT_UPLOADING:	"Uploading ...",
	TXT_UPLOADING_COMP:	"Upload complete",
	TXT_UPLOADING_COMP_Q:	"Upload queue complete",
	TXT_REMOTE_SITE_VIEW:	"View remote site",
	TXT_UPDATE:	"Update",
	TXT_CONNECTION_UPDATE:	"Connection / Update",
	TXT_SERVER_NO_SFTP:	"* It can not be displayed with SFTP connection.",
	TXT_DOWNLOAD:	"Download",
	TXT_USER_NAME:	"User name",
	TXT_MF_PATH:	"File / Folder",
	TXT_MF_DATE:	"Modify / addition date and time",
	TXT_MF_USER:	"Modify / adders",
	TXT_CLEAR_ALL:	"Clear all logs",
	TXT_CLEAR:	"Clear selected log",
	TXT_ALL_SELECT:	"Select all",
	TXT_UN_SELECT:	"Deselect",
	TXT_ERROR_MF:	"Please set the connection setting name first.",
	TXT_SAVE_LOCAL_PATH:	"Select save folder",
	TXT_IS_IT_REALLY_GOOD:	"Is it really good?",
	TXT_RECRNT_CHANGE_FILE_SEARCH:	"Search recently modified files",
	TXT_RECRNT_CHANGE_FILE_2:	"The last modified period is",
	TXT_RECRNT_CHANGE_FILE_3:	"Within days",
	TXT_SEARCH:	"Search",
	TXT_SEARCHING:	"Searching",
	TXT_TARGET_FORDER:	"Target folder",
	TXT_EXCLUSION:	"Exclusion"
	
	
	
});