define({
	
	// EXTENSION.
	EXTENSION_NAME: "Einfacher SFTP Upload",
	
	TXT_SETTING:	"Speicherort der Verbindungseinstellungen-Datei",
	TXT_SETTING_ERROR:	"Speicherort der Verbindungseinstellungen-Datei ist nicht gesetzt.",
	TXT_CONNECTING_SETTING:	"FTP/SFTP Verbindungseinstellung",
	TXT_FTP_SETTING:	"FTP/SFTP Einstellung",
	TXT_FTP_LOG:	"FTP/SFTP Verbindungsprotokoll",
	TXT_REFERENCE:	"Referenz",
	TXT_TEST_UPLOAD:	"[SSFTP] Hochladen in Testumgebung",
	TXT_TEST_UPLOAD2:	"Hochladen in Testumgebung",
	TXT_TEST_UPLOAD2:	"Hochladen in Testumgebung",
	TXT_SELECT_UPLOAD:	"[SSFTP] Auswahldatei hochladen",
	TXT_PRODUCTION_UPLOAD:	"[SSFTP] Hochladen in Produktivumgebung",
	TXT_PRODUCTION_UPLOAD2:	"Hochladen in Produktivumgebung",
	TXT_ADD_MODIFY_LOG:	"[SSFTP] Zum Änderungsprotokoll hinzufügen",
	TXT_MODIFY_LOG:	"Protokoll anpassen",
	TXT_LOCAL_SAVE:	"In lokalem Ordner speichern",
	TXT_STORAGE_LOCATION:	"Speicherort",
	TXT_SELECT_SAVE_FOLDER:	"Speicherordner auswählen",
	TXT_CONNECTION_1:	"Bitte geben Sie den Ort an um die Verbindungseinstellungen-Datei zu speichern.",
	TXT_CONNECTION_2:	"* Bitte speichern Sie nicht an der Stelle, um sie auf dem Server zu veröffentlichen.",
	TXT_CONNECTION_3:	"* Die Verbindungseinstellungen-Datei von allen Projekten ist gespeichert.",
	TXT_SETTINGS_DIALOG_TYPE_FTP:	"FTP",
	TXT_SETTINGS_DIALOG_TYPE_SFTP:	"SFTP(SSH)",
	TXT_SETTINGS_DIALOG_TYPE_LOCAL:	"Lokal",
	TXT_CONNECTION_SETTING_NAME:	"Name der Verbindungseinstellung",
	TXT_TESTING_ENVIRONMENT:	"Testumgebung",
	TXT_TESTING_ENVIRONMENT_OPEN:	"Testumgebung",
	TXT_PRODUCTION_ENVIRONMENT:	"Produktivumgebung",
	TXT_PRODUCTION_ENVIRONMENT_OPEN:	"Öffne Produktivumgebung",
	TXT_CONNECTION_TYPE:	"Typ",
	TXT_CONNECTION_HOST:	"Host",
	TXT_CONNECTION_PORT:	"Port",
	TXT_CONNECTION_USER_NAME:	"Benutzername",
	TXT_CONNECTION_PASSWORD:	"Passwort",
	TXT_CONNECTION_RSA:	"RSA Privater Schlüssel",
	TXT_CONNECTION_SERVER_PATH:	"Serverpfad",
	TXT_CONNECTION_UPLOAD_ON_SAVE:	"Hochladen beim Speichern",
	TXT_CONNECTION_SETTING_LOAD:	"Lese Konfigurationsdatei",
	TXT_CONNECTION_SITE_URL:	"Öffentlicher Pfad",
	TXT_NO_CONNECTION_HOST:	"Verbindungsziel ist nicht gesetzt.",
	TXT_START_UPLOADING:	"Hochladen starten",
	TXT_START_UPLOADING_Q:	"Hochladen der Warteschlange starten",
	TXT_START_UPLOADING_Q_NOW:	"Hochladen der Warteschlange läuft",
	TXT_UPLOADING:	"Wird hochgeladen ...",
	TXT_UPLOADING_COMP:	"Hochladen abgeschlossen",
	TXT_UPLOADING_COMP_Q:	"Hochladen der Warteschlange abgeschlossen",
	TXT_REMOTE_SITE_VIEW:	"Entfernte Seite ansehen",
	TXT_UPDATE:	"Aktualisieren",
	TXT_CONNECTION_UPDATE:	"Verbindung / Aktualisieren",
	TXT_SERVER_NO_SFTP:	"* Kann nicht mit einer SFTP Verbindung angezeigt werdenn.",
	TXT_DOWNLOAD:	"Herunterladen",
	TXT_USER_NAME:	"Benutzername",
	TXT_MF_PATH:	"Datei / Ordner",
	TXT_MF_DATE:	"Bearbeitet / Zeitpunkt des Hinzufügens",
	TXT_MF_USER:	"Bearbeitet / Nutzer",
	TXT_CLEAR_ALL:	"Alle Protokolle leeren",
	TXT_CLEAR:	"Ausgewähltes Protokoll leeren",
	TXT_ALL_SELECT:	"Alles auswählen",
	TXT_UN_SELECT:	"Auswahl aufheben",
	TXT_ERROR_MF:	"Bitte vergebe erst einen Namen für die Verbindungseinstellung.",
	TXT_SAVE_LOCAL_PATH:	"Speicherordner auswählen",
	TXT_IS_IT_REALLY_GOOD:	"Ist es wirklich gut?",
	TXT_RECRNT_CHANGE_FILE_SEARCH:	"Zuletzt geänderte Dateien durchsuchen",
	TXT_RECRNT_CHANGE_FILE_2:	"Der zuletzt geänderte Periode ist",
	TXT_RECRNT_CHANGE_FILE_3:	"Innerhalb von Tagen",
	TXT_SEARCH:	"Suche",
	TXT_SEARCHING:	"Sucht",
	TXT_TARGET_FORDER:	"Zielordner",
	TXT_EXCLUSION:	"Ausschluss"
	
});