define({
	
	// EXTENSION.
	EXTENSION_NAME: "簡単SFTP",
	
	TXT_SETTING:	"接続設定ファイル保存場所",
	TXT_SETTING_ERROR:	"接続設定ファイル保存場所が設定されていません。",
	TXT_CONNECTING_SETTING:	"FTP/SFTP接続設定",
	TXT_FTP_SETTING:	"FTP/SFTP設定",
	TXT_FTP_LOG:	"FTP/SFTP接続ログ",
	TXT_REFERENCE:	"参照",
	TXT_SELECT_UPLOAD:	"【簡単SFTP】 選択範囲ファイルのアップロード",
	TXT_SELECT_UPLOAD2:	"選択範囲ファイルのアップロード",
	TXT_TEST_UPLOAD:	"【簡単SFTP】 テスト環境にアップロード",
	TXT_TEST_UPLOAD2:	"テスト環境にアップロード",
	TXT_PRODUCTION_UPLOAD:	"【簡単SFTP】 本番環境にアップロード",
	TXT_PRODUCTION_UPLOAD2:	"本番環境にアップロード",
	TXT_ADD_MODIFY_LOG:	"【簡単SFTP】 変更ログに追加",
	TXT_MODIFY_LOG:	"変更ログ",
	TXT_LOCAL_SAVE:	"ローカルフォルダに保存",
	TXT_STORAGE_LOCATION:	"保存場所",
	TXT_SELECT_SAVE_FOLDER:	"保存フォルダを選択",
	TXT_CONNECTION_1:	"接続設定ファイルを保存する場所を指定してください。",
	TXT_CONNECTION_2:	"※サーバーに公開する場所には保存しないでください。",
	TXT_CONNECTION_3:	"※すべてのプロジェクトの接続設定ファイルが保存されます。",
	TXT_SETTINGS_DIALOG_TYPE_FTP:	"FTP",
	TXT_SETTINGS_DIALOG_TYPE_SFTP:	"SFTP(SSH)",
	TXT_SETTINGS_DIALOG_TYPE_LOCAL:	"ローカルフォルダ",
	TXT_CONNECTION_SETTING_NAME:	"接続設定名",
	TXT_TESTING_ENVIRONMENT:	"テスト環境",
	TXT_TESTING_ENVIRONMENT_OPEN:	"テスト環境を開く",
	TXT_PRODUCTION_ENVIRONMENT:	"本番環境",
	TXT_PRODUCTION_ENVIRONMENT_OPEN:	"本番環境を開く",
	TXT_CONNECTION_TYPE:	"接続方法",
	TXT_CONNECTION_HOST:	"接続先",
	TXT_CONNECTION_PORT:	"Port",
	TXT_CONNECTION_USER_NAME:	"ユーザー名",
	TXT_CONNECTION_PASSWORD:	"パスワード",
	TXT_CONNECTION_RSA:	"RSA key",
	TXT_CONNECTION_SERVER_PATH:	"サーバーパス",
	TXT_CONNECTION_UPLOAD_ON_SAVE:	"保存時アップロード",
	TXT_CONNECTION_SETTING_LOAD:	"設定ファイル参照",
	TXT_CONNECTION_SITE_URL:	"公開パス",
	TXT_NO_CONNECTION_HOST:	"接続先が設定されていません。",
	TXT_START_UPLOADING:	"アップロード開始",
	TXT_START_UPLOADING_Q:	"アップロードキュー開始",
	TXT_START_UPLOADING_Q_NOW:	"アップロードキューの実行中",
	TXT_UPLOADING:	"アップロード中 ...",
	TXT_UPLOADING_COMP:	"アップロード完了",
	TXT_UPLOADING_COMP_Q:	"アップロードキュー完了",
	TXT_REMOTE_SITE_VIEW:	"リモートサイトの表示",
	TXT_UPDATE:	"更新",
	TXT_CONNECTION_UPDATE:	"接続／更新",
	TXT_SERVER_NO_SFTP:	"※SFTP接続では表示できません。",
	TXT_DOWNLOAD:	"ダウンロード",
	TXT_USER_NAME:	"利用者名",
	TXT_MF_PATH:	"ファイル/フォルダ",
	TXT_MF_DATE:	"変更/追加日時",
	TXT_MF_USER:	"変更/追加者",
	TXT_CLEAR_ALL:	"全てのログのクリア",
	TXT_CLEAR:	"選択ログのクリア",
	TXT_ALL_SELECT:	"全て選択",
	TXT_UN_SELECT:	"選択解除",
	TXT_ERROR_MF:	"接続設定名を先に設定してください。",
	TXT_SAVE_LOCAL_PATH:	"保存フォルダを選択",
	TXT_IS_IT_REALLY_GOOD:	"本当にいいですか？",
	TXT_RECRNT_CHANGE_FILE_SEARCH:	"最近修正したファイルを検索",
	TXT_RECRNT_CHANGE_FILE_2:	"最後に修正された期間が",
	TXT_RECRNT_CHANGE_FILE_3:	"日以内",
	TXT_SEARCH:	"検索",
	TXT_SEARCHING:	"検索中…",
	TXT_TARGET_FORDER:"対象フォルダ",
	TXT_EXCLUSION:	"除外"
	
});